const puppeteer = require('puppeteer');
const path = require('path');
const fs = require('fs');

let browser = null;

/**
 * Initialize Puppeteer browser (single instance)
 */
async function getBrowser() {
    if (!browser) {
        browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
    }
    return browser;
}

/**
 * Generate HTML content for leaderboard
 */
function generateLeaderboardHTML(topUsers, guildMembers, currentUserId) {
    // Get top 3
    const top3Users = topUsers.slice(0, 3);
    const restUsers = topUsers.slice(3);

    // Build HTML for top 3
    const top3HTML = top3Users.map((user, index) => {
        const member = guildMembers.get(user.userId);
        const name = member ? member.displayName : user.userId.slice(0, 8);
        const isCurrentUser = currentUserId && user.userId === currentUserId;
        const mins = Math.floor(user.seconds / 60);
        
        const avatar = member ? member.user.displayAvatarURL({ extension: 'png', size: 256 }) : '';
        const position = index === 0 ? 'center' : (index === 1 ? 'left' : 'right');
        
        return `
            <div id="rank-${index + 1}" class="podium-item ${position}">
                <div class="icon">${['👑', '🥈', '🥉'][index]}</div>
                <div class="avatar" style="background-image: url('${avatar}')"></div>
                <div class="name${isCurrentUser ? ' highlight' : ''}">${name}</div>
                <div class="time">${mins}m</div>
            </div>
        `;
    }).join('');

    // Build HTML for rest users
    const restHTML = restUsers.map((user, index) => {
        const member = guildMembers.get(user.userId);
        const name = member ? member.displayName : user.userId.slice(0, 12);
        const isCurrentUser = currentUserId && user.userId === currentUserId;
        const totalMins = Math.floor(user.seconds / 60);
        const totalSecs = user.seconds % 60;
        const avatar = member ? member.user.displayAvatarURL({ extension: 'png', size: 128 }) : '';
        const rank = index + 4;
        
        return `
            <div class="user-item${isCurrentUser ? ' highlight' : ''}">
                <div class="user-rank">${rank}</div>
                <div class="user-avatar" style="background-image: url('${avatar}')"></div>
                <div class="user-info">
                    <div class="user-name${isCurrentUser ? ' highlight' : ''}">${name}</div>
                    <div class="user-time${isCurrentUser ? ' highlight' : ''}">${totalMins}m ${totalSecs}s</div>
                </div>
            </div>
        `;
    }).join('');

    // Read and inject data into HTML
    const htmlPath = path.join(__dirname, '../public/leaderboard.html');
    let html = fs.readFileSync(htmlPath, 'utf8');
    
    // Replace placeholders
    html = html.replace('<!-- Generated by JavaScript -->', restHTML);
    
    // Inject top 3 data
    for (let i = 0; i < top3Users.length; i++) {
        const user = top3Users[i];
        const member = guildMembers.get(user.userId);
        const name = member ? member.displayName : user.userId.slice(0, 8);
        const isCurrentUser = currentUserId && user.userId === currentUserId;
        const mins = Math.floor(user.seconds / 60);
        const avatar = member ? member.user.displayAvatarURL({ extension: 'png', size: 256 }) : '';
        
        const rankId = `rank-${i + 1}`;
        html = html.replace(
            `<div id="${rankId}"`,
            `<div id="${rankId}" style="--avatar-bg: url('${avatar}')"`
        );
    }

    return html;
}

/**
 * Convert leaderboard HTML to PNG screenshot
 */
async function renderLeaderboardScreenshot(topUsers, guildMembers, currentUserId = null) {
    try {
        const browser = await getBrowser();
        const page = await browser.newPage();
        
        // Set viewport
        await page.setViewport({ width: 1200, height: 1000 });
        
        // Generate HTML content
        const html = generateLeaderboardHTML(topUsers, guildMembers, currentUserId);
        
        // Load HTML into page
        await page.setContent(html, { waitUntil: 'networkidle2', timeout: 10000 });
        
        // Wait for images to load
        await page.waitForTimeout(1000);
        
        // Screenshot
        const screenshot = await page.screenshot({ type: 'png', fullPage: true });
        
        await page.close();
        
        return screenshot;
    } catch (error) {
        console.error('Error rendering leaderboard screenshot:', error);
        throw error;
    }
}

/**
 * Close browser on app shutdown
 */
async function closeBrowser() {
    if (browser) {
        await browser.close();
        browser = null;
    }
}

module.exports = {
    renderLeaderboardScreenshot,
    closeBrowser
};
